import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Link from "next/link";
import getTopics from "@/api_requests/get_topics";
import My_nav from "@/components/My_nav/My_nav";

// import ""
import { FaInstagramSquare, FaLinkedin, FaFacebook } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const django_topics = await getTopics();

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Script
          src="/js/jquery-3.7.1.min.js"
          id="jquery_min"
          strategy="beforeInteractive"
        />
        <Script
          id="nav_bar"
          src="/js/navbar_animate.js"
          strategy="beforeInteractive"
        /> */}
        <main className="flex relative">
          <My_nav django_topics={django_topics} />
          <section className="w-full overflow-x-clip">
            {children}
            <footer className="flex justify-between align-middle bg-yellow-200 p-3">
              <span className="flex text-center">Contact me @</span>
              <span className="flex  justify-between">
                <FaInstagramSquare size={30} className="inline-block mx-5" />
                <FaLinkedin size={30} className="inline-block mx-5" />
                <FaFacebook size={30} className="inline-block mx-5" />
              </span>
            </footer>
          </section>
        </main>
      </body>
    </html>
  );
}

//  w-28   ml-28
