import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Link from "next/link";
import getTopics from "@/api_requests/get_topics";
import My_nav from "@/components/My_nav/My_nav";

// import ""
import { FaInstagramSquare, FaLinkedin, FaTwitterSquare } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export const dynamic = "force-dynamic";
export const fetchCache = "force-no-store";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const django_topics = await getTopics();

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Script
          src="/js/jquery-3.7.1.min.js"
          id="jquery_min"
          strategy="beforeInteractive"
        />
        <Script
          id="nav_bar"
          src="/js/navbar_animate.js"
          strategy="beforeInteractive"
        /> */}
        <main className="flex relative">
          <My_nav django_topics={django_topics} />
          <section className="w-full overflow-x-clip">
            {children}
            <footer className="flex justify-between items-center bg-yellow-100 p-3">
              <span className="flex text-center">Contact me @</span>
              <span className="flex  justify-between">
                <a target="_blank" href="https://www.instagram.com/_sir_dd_/">
                  <FaInstagramSquare size={30} className="inline-block mx-5" />
                </a>

                <a
                  target="_blank"
                  href="https://www.linkedin.com/in/destiny-abhuluimen-20bb3726a"
                >
                  <FaLinkedin size={30} className="inline-block mx-5" />
                </a>
                <a
                  target="_blank"
                  href="https://twitter.com/HavenDd51034?t=yNoSFxCjTg_Ilrm3QJa1SA&s=35"
                >
                  <FaTwitterSquare size={30} className="inline-block mx-5" />
                </a>
              </span>
            </footer>
          </section>
        </main>
      </body>
    </html>
  );
}

//  w-28   ml-28
